version: '3.8'
services:
  pg:
    image: "postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/pg:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
